server:
  port: 8762

spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
security:
  basic:
    enabled: true
  user:
    name: eureka
    password: 123
